apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "userbenchmark-bot.fullname" . }}
  labels:
    {{ include "userbenchmark-bot.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.envVars | nindent 2 }}
